import json
import re
from pathlib import Path

from faker import Faker


fake = Faker("en_IN")


class Anonymizer:

    def __init__(self, map_file):

        self.map_file = Path(map_file)

        self.replacements = self.load_map()

        # Values generated by Faker.
        #
        # This prevents generated fake values from
        # being detected again as original PII.
        self.generated_values = set()

        for category in self.replacements.values():

            if not isinstance(category, dict):
                continue

            for value in category.values():

                self.generated_values.add(
                    value
                )

    clean_original = re.sub(
        r"\s+",
        " ",
        original.strip()
    )

    self.replacements[pii_type][clean_original] = replacement

    def load_map(self):

        if not self.map_file.exists():
            return {}

        try:

            with open(
                self.map_file,
                "r",
                encoding="utf-8"
            ) as file:

                data = json.load(file)

                if isinstance(data, dict):
                    return data

        except (
            OSError,
            json.JSONDecodeError
        ):

            print(
                "Warning: Could not load "
                "replacement map."
            )

        return {}

    def save_map(self):

        self.map_file.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        with open(
            self.map_file,
            "w",
            encoding="utf-8"
        ) as file:

            json.dump(
                self.replacements,
                file,
                indent=4,
                ensure_ascii=False
            )

    def get_replacement(
        self,
        pii_type,
        original
    ):

        if pii_type not in self.replacements:

            self.replacements[pii_type] = {}

        normalized = self.normalize(
            original
        )

        # Look for an existing mapping.
        #
        # Case and whitespace insensitive.
        for (
            stored_value,
            replacement
        ) in self.replacements[
            pii_type
        ].items():

            if (
                self.normalize(stored_value)
                == normalized
            ):

                return replacement

        # No existing mapping.
        replacement = self.generate_unique_value(
            pii_type
        )

        self.replacements[
            pii_type
        ][original] = replacement

        self.generated_values.add(
            replacement
        )

        return replacement

    def generate_unique_value(self, pii_type):

        while True:

            value = self.generate_fake_value(
                pii_type
            )

            if value not in self.generated_values:

                return value

    def generate_fake_value(self, pii_type):

        if pii_type == "PERSON":
            return fake.name()

        if pii_type == "EMAIL":
            return fake.email()

        if pii_type == "PHONE":
            return (
                "+91 "
                + fake.numerify(
                    "9#########"
                )
            )

        if pii_type == "ORGANIZATION":
            return fake.company()

        if pii_type == "DATE":
            return fake.date(
                pattern="%d %B %Y"
            )

        if pii_type == "SSN":
            return fake.ssn()

        if pii_type == "CREDIT_CARD":
            return fake.credit_card_number()

        if pii_type == "IP_ADDRESS":
            return fake.ipv4()

        return "[REDACTED]"